### PR TITLE
Fe 43 implement help page

### PR DESCRIPTION
**Pull request by romeoscript**

### CODE REVIEW

**Comment by isoteriksoftware** [comment]
@romeoscript please fix the conflict here

**Review by isoteriksoftware — CHANGES_REQUESTED** [review]
Please use SVG images

**Comment by rahmlad-aramide** [comment]
> Please use SVG images

Should the PR be closed for him to do the updated and send a PR again?

**Comment by isoteriksoftware** [comment]
@rahmlad-aramide He can make the changes and push to his branch. The PR will be updated

**Pull request merged**
