### PR TITLE
Fe 61 implement the 404 page

### PR DESCRIPTION
**Pull request by romeoscript**

### CODE REVIEW

**Comment by isoteriksoftware** [comment]
@romeoscript please fix the conflicts

**Review by isoteriksoftware — CHANGES_REQUESTED** [review]
Please use SVG images

**Comment by rahmlad-aramide** [comment]
> Please use SVG images

And this too?

**Review by isoteriksoftware — CHANGES_REQUESTED** [review]
You still have PNG images

**Pull request merged**
